Large number of minor fixes:
Turn up arpeggios + chords - DONE
Control mastr pitch on chord - DONE
Get bass note of arpeggios sorted - DONE?
Madness needs a much MUCH slower fade in - DONE
Add a SEND BLEEP button - DONE
UnresolvedAddressException: I think it fails to see the laptop - DONE?
Contact needs to send to each PI incrementally, exception on each send -
DONE
PIs should report which PIPOs have been loaded (most recently) - DONE
Narrow the lines - DONE
Need to know which ball is which - DONE (using the bleep button??)
Add a “Send All” command button - DONE